### ISSUE TITLE
English and moon

### ISSUE THREAD

**Issue by bksubhuti** [mixin27/flutter-mmcalendar#1]
Mingalarbar.. I make Buddhist Sun App and I've been asked to add upo ne and moon.  I don't have much mm knowledge.
Is it possible that your app supports english language and moon requests.?

**Comment by mixin27** [comment]
Hello Ashin @bksubhuti, could you explain more details?

**Comment by bksubhuti** [comment]
Oh.. i'm glad you have contacted me.
There is an app on the app store called Buddhist Sun.
People have been after me to make a moon app to know the upo-ney
There is a moon - phase app.  This could be good.  I have it working and
I'm able to get the moonphase from it.

The idea of when a full moon is complex.. it seems to also vary from
tradition to tradition.
I'm living in Sri Lanka now.  The dates are not synchronized with MM.

I'm not sure your app has english on it to get the moon phase.. or to get
the uposatha.
if it had that, I think I could maybe work with it.

I'll try clone your project and see more about the data it gives me.  From
reading, I think it is more for mm text.

You can see the buddhist sun app in the app store.
I also manage the project for tipitaka pali reader (fluttter sqlite) ..
main (80%) code written by ven pndazza.  I've added some code and also use
a bulgarian programmer.  These days, I just use cgpt+ for most of what I do
with minor edits.  (and I slowly forget flutter).

Bhante Subhuti

https://AmericanMonk.org
https://withmetta.net

**Comment by bksubhuti** [comment]
The moon and holidays will be new for the next update (plus material 3)
https://github.com/mixin27/flutter-mmcalendar/assets/18184280/32acae01-191b-463f-820d-d700e33718ad

![image](https://github.com/mixin27/flutter-mmcalendar/assets/18184280/375033e4-7752-4a4f-a935-1e67d8c99589)

![image](https://github.com/mixin27/flutter-mmcalendar/assets/18184280/ca5c83d9-0cba-411b-a0af-1ecbd6506903)

**Comment by bksubhuti** [comment]
So I now know what I need.  I need to get smaller atomic information from String formatByPatternAndLanguage({
    .. like full moon day new moon day.. 
    I'd also like the number day like classic mm calendars.
    
![image](https://github.com/mixin27/flutter-mmcalendar/assets/18184280/fd63a1ac-cf8a-4a5a-9bcf-ee7fbfeb7b64)

**Comment by mixin27** [comment]
Yes you can.

But if you want to get specific value date, you can get from `MyanmarDate` model extension functions.

Example:
```dart
final mmDate = MyanmarDateConverter.fromDateTime(DateTime.now());

mmDate.getMonthName();
mmDate.getBuddhistEra();

// and more...
```

**Comment by bksubhuti** [comment]
Yes.. it seems to work as you said.
It looks like I will be using your library for our app along with the moon
phase library..
Not so big.. but around 500 active installs .
Tipitaka Pali Reader has 3000+ active installations.
Sadhu x 3

Bhante Subhuti

https://AmericanMonk.org
https://withmetta.net
